name: ticketscraper_dbt_duckdb

version: 1.0.0

config-version: 2

profile: ticketscraper_dbt_duckdb

model-paths:
  - models

analysis-paths:
  - analyses

test-paths:
  - tests

seed-paths:
  - seeds

macro-paths:
  - macros

snapshot-paths:
  - snapshots

target-path: target

clean-targets:
  - target
  - dbt_packages

models:
  ticketscraper_dbt_duckdb:
    example:
      +materialized: view

vars:
  data_diff:
    prod_schema: main
