
version: 2

models:
  - name: stg_listings_sold
    description: ""
    columns:
      - name: updated
        description: ""
        data_type: timestamp

      - name: id
        description: ""

      - name: description
        description: ""

      - name: event_name
        description: ""

      - name: event_start_date
        description: ""

      - name: event_end_date
        description: ""

      - name: amount_of_listings
        description: ""

      - name: entrance_title
        description: ""

      - name: entrance_id
        description: ""

      - name: original_price
        description: ""

      - name: price
        description: ""

      - name: location
        description: ""

      - name: city
        description: ""

      - name: url
        description: ""

      - name: status
        description: ""

      - name: seller_name
        description: ""

      - name: seller_id
        description: ""
