name: "DBT Run"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00 pm

jobs:
  dbt:
    name: "Run dbt"
    permissions: write-all
    container: python:3.9
    runs-on: ubuntu-latest
    environment:
      name: dbt
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      motherduck_token: ${{ secrets.MOTHERDUCK_TOKEN }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: pip install
        run: pip install poetry

      - name: poetry install
        run: poetry install

      - name: run sqlfluff
        run: poetry run sqlfluff format models --dialect duckdb || true

      - name: dbt deps
        run: poetry run dbt deps

      - name: dbt source freshness
        run: poetry run dbt source freshness --profiles-dir .

      - name: dbt build
        run: poetry run dbt build --profiles-dir .

      - name: Setup DBT Docs to GH Pages
        uses: actions/configure-pages@v3

      - name: Generate docs
        run: poetry run dbt docs generate --profiles-dir .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the target directory containing the docs
          path: "target"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
