name: "DBT Run"
on:
  push:
  # schedule:
    # - cron: "16 9 * * *" # every day at 9:16 am

jobs:
  dbt:
    name: "Run dbt"
    runs-on: ubuntu-latest
    container: python:3.9
    permissions: write-all

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: pip install
        run: pip install poetry
      - name: poetry install
        run: poetry install

      - name: dbt deps
        run: poetry run dbt deps

      - name: Download the dbt.duckdb from S3
        run: poetry run python scripts/load_s3_files.py download

      - name: dbt build
        run: poetry run dbt build --profiles-dir .

      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

      - name: Upload the dbt.duckdb to S3
        run: poetry run python scripts/load_s3_files.py upload