name: "DBT Run"
on:
  push:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00 pm

jobs:
  dbt:
    name: "Run dbt"
    runs-on: ubuntu-latest
    container: python:3.9
    permissions: write-all

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: pip install
        run: pip install poetry
      - name: poetry install
        run: poetry install

      - name: run sqlfluff
        run: poetry run sqlfluff format models --dialect duckdb
      - name: dbt deps
        run: poetry run dbt deps

      - name: Download the dbt.duckdb from S3 and store MD5 hash as a variable
        id: download_and_get_md5
        run: |
          original_md5=$(poetry run python scripts/load_s3_files.py download)
          echo "::set-output name=md5::$original_md5"

      - name: dbt build
        run: poetry run dbt build --profiles-dir .

      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

      - name: Upload the dbt.duckdb to S3
        run: poetry run python scripts/load_s3_files.py upload "${{ steps.download_and_get_md5.outputs.md5 }}"