version: 2

sources:
  - name: sold
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/sold/*/*.parquet"
    tables:
      - name: sold

  - name: events
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/events/*/*.parquet"
    tables:
      - name: events