version: 2

sources:
  - name: sold
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/sold/*/*.parquet"
    tables:
      - name: sold
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: updated

  - name: events
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/v1/events.parquet"
    tables:
      - name: events

  - name: invalid_listings
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/dbt/invalid_listings.parquet"
    tables:
      - name: invalid_listings

  - name: event_cities
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/events/cities/*/*/*.parquet"
    tables:
      - name: event_cities

  - name: sold_cities
    meta:
      external_location: "s3://lbenninga-projects/ticketswap/sold/cities/*/*/*.parquet"
    tables:
      - name: sold_cities